feat(#38): make module TurboModule-compatible
LinusU/react-native-get-random-values pull request #59
Opened 2024-03-24 19:42 UTC by mateusz1913

Closes #38 

👋 This PR adds TurboModule support

List of changes:
- create JS Codegen spec
- use install_modules_dependencies util in podspec if possible, to install React deps
- migrate Android module class to conform to codegenerated spec when new arch enabled
- copy codegen-ed to oldarch Android source set to make module work when new arch disabled
- migrate iOS module class to conform to codegenerated spec when new arch enabled

2024-04-01 18:59 UTC, mateusz1913 commented
Hi @LinusU , let me know if there's anything I'd need to improve in this PR

2024-12-02 07:35 UTC, pinpong commented
@LinusU lgtm

2024-12-05 06:39 UTC, pinpong commented
@mateusz1913 is the android newarch folder missing?

2024-12-05 07:20 UTC, mateusz1913 commented
@pinpong no, the codegen spec class is used by default and if old arch enabled, it uses the class from old arch folder

2024-12-10 16:06 UTC, 818Nawaf approved these changes

2025-01-23 04:16 UTC, brentpi commented
For some reason; when using the TurboModule implementation - Sentry seems to stop generating its event identifiers correctly for me (only difference is TurboModule/non-TurboModule).  When it fails, it falls back to a static ID (10000000100040008000100000000000).

2025-01-24 11:09 UTC, brentpi requested changes

2025-01-24 11:09 UTC, brentpi commented on specs/NativeRNGetRandomValues.js
> +  +getRandomBase64: (byteLength: Int32) => string;
@mateusz1913 When running this, I needed to change this to 'Double' rather than 'Int32' to make the types match correctly in Obj-C.  

For a Uint8Array(10), byteLength in getRandomBase64 was "4621819117588971520" in the debugger, and I was receiving "Error: Exception in HostFunction: Failed to aquire secure random bytes".

Changing this type def resolves this issue.

2025-01-24 14:45 UTC, 818Nawaf approved these changes

2025-09-08 06:22 UTC, closed without merging

2025-10-22 19:02 UTC, LinusU commented
Sorry for never getting to this! I've updated to the new arch in the latest version...

It's in this release: [🚢 2.0.0 / 2025-10-22](https://github.com/LinusU/react-native-get-random-values/releases/tag/v2.0.0)